name: Webserv

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install curl

    - name: Build web server
      run: make

    - name: Start web server
      run: ./webserv config_file/default.conf

    - name: Check if server is responding
      run: |
        curl http://localhost:8080
